### PR TITLE
Update to include "Error acquiring the state lock"

### PR DESCRIPTION
**Pull request by Official-James**
- Including steps in articles/terraform/troubleshoot.md for a common issue where the state file locks. Steps provided to identify the issue, description of the cause and steps to resolve. 
- One image uploaded to use with articles/terraform/troubleshoot.md article to help readers identify the break lease button.

### CODE REVIEW

**Comment by ktoliver** [comment]
Administrative note: If the pull request is approved for merge, the image file name and its reference in the Markdown file will need to be changed to replace underscores with hyphens to match file naming standards that are in place for the content. Thanks!

**Comment by TomArcherMsft** [comment]
@Official-James Thanks much for the contribution.
@ktoliver I'm fine with the additions. #sign-off

**Comment by TomArcherMsft** [comment]
@ktoliver I'm fine creating another PR and changing that. Thanks!

**Comment by Official-James** [comment]
@TomArcherMsft @ktoliver I have made the change to remove the underscores and replace with hyphens as per naming convention. Should be good to go 👍🏼

**Comment by ktoliver** [comment]
Looks good; merging. I did a quick edit for spelling, etc. Thanks.

**Pull request merged**
