### PR TITLE
Update awesome-azd link

### PR DESCRIPTION
**Pull request by ccbarragan**
Fixes a broken link. Thanks!

### CODE REVIEW

**Comment by Jak-MS** [comment]
@alexwolfmsft 
Can you review the proposed changes? 

**Important**: When the changes are ready for publication, adding a `#sign-off` comment is the best way to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Review by alexwolfmsft — APPROVED** [review]

**Comment by alexwolfmsft** [comment]
#sign-off

**Comment by Court72** [comment]
@alexwolfmsft, @ccbarragan - This PR can't be merged with validation warnings. Can you resolve the warnings and sign off again?

**Comment by KarlErickson** [comment]
@alexwolfmsft it looks like the metadata fixes haven't yet been transferred in from the private repo. You should be able to close/reopen later today to get a clean build and then sign off. I'll do this tomorrow morning if it hasn't been merged by then.

**Pull request merged**
