### PR TITLE
Typo "a GitHub action"→"a GitHub Action"

### PR DESCRIPTION
**Pull request by hyoshioka0128**
https://docs.microsoft.com/en-us/azure/developer/github/deploy-to-azure
https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/github/deploy-to-azure.md
#PingMSFTDocs

### CODE REVIEW

**Comment by Court72** [comment]
@N-Usha 

Can you review the proposed changes? *IMPORTANT*: When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Review by N-Usha — APPROVED** [review]

**Review by N-Usha — COMMENTED** [review]
https://docs.github.com/en/actions/using-workflows. "Actions" is a noun in GitHub notation. We should not make this change and let it be.

**Review by N-Usha — CHANGES_REQUESTED** [review]
Please revert back to "Actions" or just close the PR and let the articles be as-is.

**Comment by hyoshioka0128** [comment]
"close the PR" #811 .

**Pull request closed without merging**
