### PR TITLE
Updated postman settings

### PR DESCRIPTION
**Pull request by K232**
As Web API Controller Class does not exist, I took Controller Class - empty. It has no templated class methods so I always received a 404 :-( Therefore I've added a HTTPGet so I get the 200 :-) Additionally it does not work for me with localhost:5001 but with the port specified in ssl-port.

### CODE REVIEW

**Comment by mikeparker104** [comment]
Thank you @K232 for your thorough input. Please can you confirm that these changes apply to VS Mac? The original steps were based on this environment?

**Comment by K232** [comment]
Hi @mikeparker104, no idea how it looks on VS for Mac. [Prerequisites](https://docs.microsoft.com/en-us/azure/developer/mobile-apps/notification-hubs-backend-service-xamarin-forms#prerequisites) say it's for Mac or Windows so I took windows. I don't know whether wording is different on Mac and Windows (which would be surprising?). If so, maybe add information about the naming on windows. I just tried to follow the instructions and wanted to let you know of the differences I had found on Windows.

**Comment by mikeparker104** [comment]
Hi @K232. Really appreciate you pointing out these challenges. I can see how the following wording might be ambiguous: 'The steps provided are for Visual Studio for Mac but it's possible to follow along using Visual Studio 2019'. Making this clearer and adding further information specific to Windows, where it makes sense, will make it easier to follow. Thank you again for taking the time to share this feedback.

**Comment by mikeparker104** [comment]
Thanks for the feedback @K232. I've adapted and combined it with other feedback into a single [commit](https://github.com/MicrosoftDocs/azure-dev-docs/commit/41515b073ea41d9d307736b2413d3765e50793fd).

**Comment by ktoliver** [comment]
We'll close the PR. Thanks!

**Pull request closed without merging**
