### PR TITLE
Updates to EAP on VM step-by-step guidance

### PR DESCRIPTION
**Pull request by backwind1233**
## Context 
This PR is for addressing comments by @m-reza-rahman in this [story](https://dev.azure.com/edburns-msft/Open%20Standard%20Enterprise%20Java%20(Java%20EE)%20on%20Azure/_workitems/edit/4797).

### CODE REVIEW

**Comment by Court72** [comment]
@karlerickson,

Can you review the proposed changes? 

When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by KarlErickson** [comment]
@backwind1233 can you please close this PR and reopen it in the private azure-dev-docs-pr repo? Also, if it's ready to edit and publish, please set it to "Ready for review". Thanks!

**Comment by KarlErickson** [comment]
Ping @backwind1233

**Comment by backwind1233** [comment]
Thank you @KarlErickson, I have just closed the PR.

**Comment by backwind1233** [comment]
Redirect to https://github.com/MicrosoftDocs/azure-dev-docs-pr/pull/5403

**Pull request closed without merging**
