### PR TITLE
Fix Interpolation-only expression. Bump Ubuntu.

### PR DESCRIPTION
**Pull request by davemasino**
Fixes Issue 313

### CODE REVIEW

**Comment by davemasino** [comment]
Also cleaned up Markdown whitepsace as per VS Code linter

**Comment by TomArcherMsft** [comment]
Fixes issue #313

**Comment by TomArcherMsft** [comment]
@davemasino Thanks for the feedback. Fixes look good. Merging now.

**Comment by davemasino** [comment]
I submitted another PR to fix the other two spots where Ubuntu version was specified. Thanks for the tutorial!

**Pull request merged**
