### PR TITLE
Fix github/connect-from-azure.md yaml alignments

### PR DESCRIPTION
**Pull request by asbiin**
The latest `Log in with Azure` example wouldn't work..

### CODE REVIEW

**Comment by Court72** [comment]
@MoChilia

Can you review the proposed changes? 

When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Review by MoChilia — COMMENTED** [review]
Thank you for reporting this! Please also include the suggested changes.

**Comment by KarlErickson** [comment]
Hi @MoChilia I went ahead and committed your suggested changes. If there is nothing more to do, please go ahead and `#sign-off`. Thanks!

**Comment by KarlErickson** [comment]
Ping @MoChilia

**Review by MoChilia — APPROVED** [review]

**Comment by MoChilia** [comment]
#sign-off

**Pull request merged**
