### PR TITLE
Update connect-from-azure.md

### PR DESCRIPTION
**Pull request by sneakernuts**
The service principal does not need full contributor rights on the subscription itself. Documentation needs to clarify that it's possible to assign contributor rights to the resources (i.e. resource group) for the service principal to perform actions. Ideally we will apply the principle of least privilege when granting permissions.

### CODE REVIEW

**Comment by ktoliver** [comment]
Hi @juliakm - Is this a PR you can review? (It looks like the metadata needs to be updated for author.) Note that "resource" has a misspelling. 

Thanks!

**Review by sneakernuts — COMMENTED** [review]
typo :P

**Comment by KathrynEE** [comment]
@ktoliver - I don't have ability to approve the PR. I believe @mijacobs does, or will know who can approve.

**Comment by sneakernuts** [comment]
Any updates on this? Thanks!

**Comment by mijacobs** [comment]
@juliakm or @N-Usha , can one of you take a look at this PR and approve it?

**Comment by juliakm** [comment]
I think that the current text is correct because active directory applications are tied to a subscription (Article: [assign a role to the application](https://docs.microsoft.com/azure/active-directory/develop/howto-create-service-principal-portal#assign-a-role-to-the-application)). I'll confirm this with the product team.

**Review by KathrynEE — APPROVED** [review]

**Pull request merged**
