### PR TITLE
Made it clear that federated credentials are still in preview

### PR DESCRIPTION
**Pull request by derek-wade**

### CODE REVIEW

**Comment by Jak-MS** [comment]
IMPORTANT: When this content is ready to merge, the reviewer must add `#sign-off` in a comment or the approval may get overlooked.


#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by Jak-MS** [comment]
@TomArcherMsft - not sure if this falls under your purview, but tagging you just in case.

**Comment by TomArcher** [comment]
@Jak-MS This is not me. Ping me offline and I can send you some possible owners.

**Comment by derek-wade** [comment]
It's important to note that federated credentials are still in preview. This documentation page provides thorough enough details that a user could successfully implement the Azure Login action using OIDC in their production environment without realizing it depends on an Azure AD feature still in preview.

**Comment by KarlErickson** [comment]
@N-Usha can you review and approve or close if this is no longer relevant? Thanks!

**Review by N-Usha — APPROVED** [review]

**Pull request merged**
