### PR TITLE
bug: command output to match docs

### PR DESCRIPTION
**Pull request by burhan**
The documentation states _The value of the `object-id` is the `appId`_ but the command uses `--spn` which doesn't match what is expected, and for me, it only worked with `--object-id`.

### CODE REVIEW

**Comment by KarlErickson** [comment]
@edburns can you verify? Thanks.

**Comment by KarlErickson** [comment]
@edburns ping

**Comment by edburns** [comment]
FYI:

> While it looks safe to me, I am unable to approve it in good faith without first testing it.  If any of you have time to do it today before I start my day tomorrow, please see if the article can be executed as written in the preview link.  Otherwise, I'll do it when I have time.

Asked my team for help reviewing.

**Comment by edburns** [comment]
@burhan Hi, thanks for your contribution. I want to review the steps in the doc, including your changes, to verify they still all work together. Please be patient as we I do these steps.

**Comment by zhengchang907** [comment]
Azure CLI version: 2.35.0

In doc it says 'The value of the object-id is the appId' is wrong, they are not the same value.

However, using `--object-id` doesn't work for me, the key vault settings outcome is like:
image

And the correct settings should like:
image
This can be achieved by running `az keyvault set-policy --name <key-vault-name> --spn <name field of command `az ad sp create-for-rbac`> --secret-permissions get list

**Review by edburns — CHANGES_REQUESTED** [review]
Please see [these comments](https://github.com/MicrosoftDocs/azure-dev-docs/pull/712#issuecomment-1091310035) and make the requested changes before re-applying for review.

**Comment by KarlErickson** [comment]
This PR is obsolete; doc has been updated.

**Pull request closed without merging**
