### PR TITLE
Initial commit for adding Pulumi

### PR DESCRIPTION
**Pull request by jkodroff**
Hello, good people of MSFT. I'm a Solutions Architect for Pulumi and I wanted to start the process to try to get Pulumi added to the Azure dev docs. I've started this PR as a way to get the convo going as well as to demonstrate the work we've done on our end.

Some open questions:

* Does this repo accept outside contributions? (There's no CONTRIBUTING doc, so it's not totally clear to me.) If not, what would the process be to get Pulumi added to the Azure docs and how could I help move that process along?
* Assuming outside contributions are welcome, what would an MVP be for an acceptable PR? I'm basing my work of the TF docs, but those docs are quite extensive and I didn't want to invest a ton of time before I got some feedback. For example, "We need instructions for Bash and PowerShell, plus at least one tutorial."
* Any feedback on the work done so far in this PR?

Assuming that Azure is interested and the minimum requirements for a PR to be accepted are clarified, I figure this PR should be marked as a draft. Once I have something ready to commit I figure I'll open a fresh PR.

Thanks so much!

### CODE REVIEW

**Comment by cmcclister** [comment]
Learn Build status updates of commit _[4350d42](https://github.com/jkodroff/azure-dev-docs/commits/4350d422cb0183deb74a25eb33a1ba44f2d133f7)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.learn.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[articles/pulumi/authenticate-to-azure.md](https://github.com/jkodroff/azure-dev-docs/blob/add-pulumi/articles/pulumi/authenticate-to-azure.md) | :x:Error | | [Details](#user-content-65c0f151dacf8b4ceb792bcc4f7d4e2d-08bb07d8)
[articles/pulumi/get-started-cloud-shell-bash.md](https://github.com/jkodroff/azure-dev-docs/blob/add-pulumi/articles/pulumi/get-started-cloud-shell-bash.md) | :x:Error | | [Details](#user-content-2389d83231c04897799d7c9745f21f05-08bb07d8)
[articles/pulumi/index.yml](https://github.com/jkodroff/azure-dev-docs/blob/add-pulumi/articles/pulumi/index.yml) | :warning:Warning | | [Details](#user-content-3a4c573b2207b7a67c4e05e91c60a7bd-08bb07d8)
[articles/pulumi/overview.md](https://github.com/jkodroff/azure-dev-docs/blob/add-pulumi/articles/pulumi/overview.md) | :warning:Warning | | [Details](#user-content-05f5fc6f9ed9f43b68c2cfab746eca85-08bb07d8)
[articles/pulumi/quickstart-configure.md](https://github.com/jkodroff/azure-dev-docs/blob/add-pulumi/articles/pulumi/quickstart-configure.md) | :warning:Warning | | [Details](#user-content-415c5160c204394ec50b52d40b6c4636-08bb07d8)

<a id="65c0f151dacf8b4ceb792bcc4f7d4e2d-08bb07d8"></a>
### [articles/pulumi/authenticate-to-azure.md](https://github.com/jkodroff/azure-dev-docs/blob/add-pulumi/articles/pulumi/authenticate-to-azure.md)
 - **Line 35, Column 1**: **[Error: include-not-found]** `````Invalid include link: 'includes/authenticate-to-azure.md'.`````
 - **Line 2, Column 1**: **[Warning: ms-prod-or-service-missing - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````
 - **Line 3, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Learn the various options to authenticate to Azure with a Microsoft Account' is duplicated in 'pulumi/authenticate-to-azure.md(3,14)', 'terraform/authenticate-to-azure.md(3,14)'.`````

<a id="2389d83231c04897799d7c9745f21f05-08bb07d8"></a>
### [articles/pulumi/get-started-cloud-shell-bash.md](https://github.com/jkodroff/azure-dev-docs/blob/add-pulumi/articles/pulumi/get-started-cloud-shell-bash.md)
 - **Line 49, Column 1**: **[Error: include-not-found]** `````Invalid include link: 'includes/authenticate-to-azure.md'.`````
 - **Line 2, Column 1**: **[Warning: ms-prod-or-service-missing - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="3a4c573b2207b7a67c4e05e91c60a7bd-08bb07d8"></a>
### [articles/pulumi/index.yml](https://github.com/jkodroff/azure-dev-docs/blob/add-pulumi/articles/pulumi/index.yml)
 - **Line 41, Column 18**: **[Warning: file-not-found - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'create-k8s-cluster-with-tf-and-aks.md'.`````

<a id="05f5fc6f9ed9f43b68c2cfab746eca85-08bb07d8"></a>
### [articles/pulumi/overview.md](https://github.com/jkodroff/azure-dev-docs/blob/add-pulumi/articles/pulumi/overview.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-or-service-missing - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="415c5160c204394ec50b52d40b6c4636-08bb07d8"></a>
### [articles/pulumi/quickstart-configure.md](https://github.com/jkodroff/azure-dev-docs/blob/add-pulumi/articles/pulumi/quickstart-configure.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-or-service-missing - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/165f6904-aea8-9c51-0a94-fc09f5b5556a/202212310233163983-1004/BuildReport?accessString=2098dbae05d532a45a8e6f802759b7cf600238da6ace19ab07911a553f2cf8f0).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.learn.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Learn Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/165f6904-aea8-9c51-0a94-fc09f5b5556a?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.learn.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

**Comment by jborsecnik** [comment]
Content owner notification email sent.

**Comment by jborsecnik** [comment]
@jkodroff - In order for us to evaluate and accept your PR, we ask that you sign a contribution license agreement. It's all electronic and will take just a few minutes: https://cla.microsoft.com. Thank you.

**Comment by jkodroff** [comment]
Thanks so much for the quick response! We're going to review the CLA internally just to make sure it works for Pulumi and will follow up soon.

**Comment by mcleanbyron** [comment]
Hello Josh - This repository is open for public contributions, but typically these contributions are smaller-scale items like bug fixes and targeted pieces of new guidance specifically about Azure development. We usually do not accept large-scale contributions related to 3rd party tools and platforms. Given this, I am closing this PR for now.

Is this submission related to an ongoing relationship or project between Pulumi and a Microsoft engineering team? If so, let's discuss. Please feel free to reach out to me directly at mcleans-at-microsoft.com.

Thanks also for pointing out the lack of contributor guidance for this docs repo. We'll get something similar to the https://github.com/MicrosoftDocs/azure-docs/blob/main/CONTRIBUTING.md file for the azure-docs repo added to this one too.

**Comment by jkodroff** [comment]
@mcleanbyron Thanks for getting back to me before I got too far down the wrong road. Much appreciated!

**Pull request closed without merging**
