### PR TITLE
Update pipeline-with-github-and-docker.md

### PR DESCRIPTION
**Pull request by mfkhan267**
Hello World line in the index.js file was incorrectly referenced to line 6 instead of line number 58.

Updated to the correct line number 58. also added the Enter Your Name attribute to the reference.

### CODE REVIEW

**Comment by TomArcherMsft** [comment]
Hi @mfkhan267 . Thanks for the feedback. What does adding 'your name' do for the sample - especially since you kept the 'world' part?

**Comment by mfkhan267** [comment]
I was trying to validate the repo as per the Azure Documentation

Azure Doc: https://learn.microsoft.com/en-us/azure/developer/jenkins/pipeline-with-github-and-docker

Repo: https://github.com/Azure-Samples/nodejs-docs-hello-world.git


and found discrepancies as below:


Document says, make changes so that it reads Hello World

[cid:af3089bd-d798-4ffd-8799-22932cec3100]

however the index.js file already has Hello World on line 58.

[cid:fc7ffeb8-4223-426b-9191-e3585ca2c5b2]

So to commit a change, the users following the document must change the response to something else like "Hello New World" or may be "Hello World <your name"

Hope this clarifies.

regards, Feroze
________________________________

**Comment by ShannonLeavitt** [comment]
@TomArcherMsft

IMPORTANT: When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by TomArcherMsft** [comment]
@mfkhan267 After internal conversation, It's been decided that Jenkins documentation support is limited to security issues only. Thanks again for taking your time to contribute, but I need to close this PR.

**Pull request closed without merging**
