### PR TITLE
Added Azure policy as code card and build vm image action

### PR DESCRIPTION
**Pull request by raiyanalam**

### CODE REVIEW

**Comment by ktoliver** [comment]
Hi @raiyanalam -- This pull request was opened in the public repo. PMs should work in the private repo, per the Microsoft Docs contributor guide. Would you make this content update in the private repo instead? Thank you! We'll close this PR.

**Comment by ktoliver** [comment]
@KathrynEE for awareness

**Comment by raiyanalam** [comment]
@ktoliver : Can you also give me the link to the Microsoft Docs contribution guide.. i will raise a separate pr.

**Comment by ktoliver** [comment]
https://review.docs.microsoft.com/help/contribute/?branch=master

Thank you.

**Pull request closed without merging**
