### PR TITLE
Extend static tutorial to include 3 major js libs

### PR DESCRIPTION
**Pull request by burkeholland**
I took a stab at extending the static site tutorial to include Angular, React and Vue. While first I thought I might create two separate tutorials, there is so much that is the same between all 3 that I went for a tabs approach. 

I'm unsure of how to preview this, so I don't know if all of the formatting is correct here. 

+ @kraigb and @fiveisprime

### CODE REVIEW

**Comment by fiveisprime** [comment]
Same, no idea how to preview so maybe Kraig can hook us up with a review link 😉

**Comment by kraigb** [comment]
@burkeholland Generally speaking, this looks good except that we can't see the preview. Like I said in email, can you close this PR and replicate it in the internal azure-dev-docs-pr repo instead? That way we'll get all the preview goodness.

**Comment by burkeholland** [comment]
Yes. I’ll work on that. On vacation this week so maybe first thing Monday.

Burke

**Comment by kraigb** [comment]
@burkeholland Can you close this PR as we merged the changes in the private repo?

**Pull request closed without merging**
