### PR TITLE
Add additional dependency for azd

### PR DESCRIPTION
**Pull request by 41vin**
Hi, I add additional dependency for azd

articles/azure-developer-cli/install-azd.md

add Install pwsh

### CODE REVIEW

**Comment by Court72** [comment]
@alexwolfmsft

Can you review the proposed changes? 

When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by Cor5in** [comment]
#sign-off

**Comment by Cor5in** [comment]
[#sign off]

**Comment by Cor5in** [comment]
#sign-off

Thanks
Kind regards

**Pull request closed without merging**
