### PR TITLE
Feature: Create a code sample using Svelte Framework - Page 02

### PR DESCRIPTION
**Pull request by glaucia86**
Creating a code sample using Svelte Framework - Page 02

### CODE REVIEW

**Comment by glaucia86** [comment]
Pull Request relationated the issue: #68 

cc: @kraigb @burkeholland

**Comment by burkeholland** [comment]
@kraigb Can we merge these?

**Comment by kraigb** [comment]
Yes, we can get these merged. However, @glaucia86, the screenshots are way too big and need to be reshot on a 100% scaling screen, otherwise they're completely oversized for the docs site. Please adjust and update the PR.

**Comment by kraigb** [comment]
Can't figure out how to fix the merge conflict, so duplicating the PR in https://github.com/MicrosoftDocs/azure-dev-docs-pr/pull/386 instead and closing this one.

**Pull request closed without merging**
