### PR TITLE
Automatic request mapping do not happen for port 8080

### LINKED ISSUE #80: Automatic mapping of Internet requests to embedded Tomcat server running in port 8080 not happening in Azure
On the note section in the following link - https://docs.microsoft.com/en-us/azure/java/spring-framework/deploy-spring-boot-java-app-on-linux#create-a-web-app-on-linux-on-azure-app-service-using-your-container-image , it is stated that "Azure will automatically map Internet requests to embedded Tomcat server that is running on the standard ports of 80 or 8080. "

But this seems to be not working. The automatic mapping happens for just port 80 and for 8080, the mapping needs to be configured in Application settings using WEBSITES_PORT setting.

During my deployment, the application dint started initially as it was running on port - 8080. But after configuring WEBSITES_PORT setting to 8080, the application deployed successfully.

Please find the sample log below which confirms the above behavior:

_2020-02-12 10:04:09.953 INFO  - Starting container for site
2020-02-12 10:04:09.953 INFO  - docker run -d -p 5400:80 --name test-service_0_9750b98c -e WEBSITES_ENABLE_APP_SERVICE_STORAGE=false -e WEBSITE_SITE_NAME=test-service -e WEBSITE_AUTH_ENABLED=False -e PORT=80 -e WEBSITE_ROLE_INSTANCE_ID=0 -e WEBSITE_HOSTNAME=test-service.azurewebsites.net -e WEBSITE_INSTANCE_ID=**** testregistry.azurecr.io/test-0.0.2:latest  

2020-02-12 10:04:09.953 INFO  - Logging is not enabled for this container.
Please use https://aka.ms/linux-diagnostics to enable logging to see container logs here.
2020-02-12 10:04:10.566 INFO  - Initiating warmup request to container test-service_0_9750b98c for site test-service
2020-02-12 10:04:25.688 INFO  - Waiting for response to warmup request for container test-service_0_9750b98c. Elapsed time = 15.1228105 sec
2020-02-12 10:04:40.795 INFO  - Waiting for response to warmup request for container test-service_0_9750b98c. Elapsed time = 30.2290628 sec
2020-02-12 10:04:55.914 INFO  - Waiting for response to warmup request for container test-service_0_9750b98c. Elapsed time = 45.3483676 sec
2020-02-12 10:05:11.007 INFO  - Waiting for response to warmup request for container test-service_0_9750b98c. Elapsed time = 60.4413502 sec
2020-02-12 10:05:26.123 INFO  - Waiting for response to warmup request for container test-service_0_9750b98c. Elapsed time = 75.5579571 sec
2020-02-12 10:05:41.211 INFO  - Waiting for response to warmup request for container test-service_0_9750b98c. Elapsed time = 90.6451878 sec
2020-02-12 10:05:56.311 INFO  - Waiting for response to warmup request for container test-service_0_9750b98c. Elapsed time = 105.7457258 sec
2020-02-12 10:06:11.428 INFO  - Waiting for response to warmup request for container test-service_0_9750b98c. Elapsed time = 120.8620846 sec
2020-02-12 10:06:26.536 INFO  - Waiting for response to warmup request for container test-service_0_9750b98c. Elapsed time = 135.9699815 sec
2020-02-12 10:06:41.638 INFO  - Waiting for response to warmup request for container test-service_0_9750b98c. Elapsed time = 151.072046 sec
2020-02-12 10:06:56.770 INFO  - Waiting for response to warmup request for container test-service_0_9750b98c. Elapsed time = 166.2044429 sec
2020-02-12 10:07:11.908 INFO  - Waiting for response to warmup request for container test-service_0_9750b98c. Elapsed time = 181.3423215 sec
2020-02-12 10:07:27.038 INFO  - Waiting for response to warmup request for container test-service_0_9750b98c. Elapsed time = 196.4720808 sec
2020-02-12 10:07:42.576 INFO  - Waiting for response to warmup request for container test-service_0_9750b98c. Elapsed time = 212.0108186 sec
2020-02-12 10:07:57.697 INFO  - Waiting for response to warmup request for container test-service_0_9750b98c. Elapsed time = 227.1315387 sec
2020-02-12 10:08:01.075 ERROR - Container test-service_0_9750b98c for site test-service did not start within expected time limit. Elapsed time = 230.5088465 sec
2020-02-12 10:08:01.100 ERROR - Container test-service_0_9750b98c didn't respond to HTTP pings on port: 80, failing site start. See container logs for debugging.
2020-02-12 10:08:01.154 INFO  - Stoping site test-service because it failed during startup.
2020-02-12 10:08:01.413 INFO  - Pulling image: testregistry.azurecr.io/test-0.0.2:latest
2020-02-12 10:08:01.605 INFO  - latest Pulling from test-0.0.2
2020-02-12 10:08:01.606 INFO  -  Digest: sha256:***
2020-02-12 10:08:01.606 INFO  -  Status: Image is up to date for testregistry.azurecr.io/test-0.0.2:latest
2020-02-12 10:08:01.610 INFO  - Pull Image successful, Time taken: 0 Minutes and 0 Seconds
2020-02-12 10:08:01.615 INFO  - Starting container for site
2020-02-12 10:08:01.616 INFO  - docker run -d -p 7202:8080 --name test-service_0_2c61c149 -e WEBSITES_ENABLE_APP_SERVICE_STORAGE=false -e WEBSITES_PORT=8080 -e WEBSITE_SITE_NAME=test-service -e WEBSITE_AUTH_ENABLED=False -e WEBSITE_ROLE_INSTANCE_ID=0 -e WEBSITE_HOSTNAME=test-service.azurewebsites.net -e WEBSITE_INSTANCE_ID=**** testregistry.azurecr.io/test-0.0.2:latest  

2020-02-12 10:08:01.616 INFO  - Logging is not enabled for this container.
Please use https://aka.ms/linux-diagnostics to enable logging to see container logs here.
2020-02-12 10:08:02.424 INFO  - Initiating warmup request to container test-service_0_2c61c149 for site test-service
2020-02-12 10:08:15.481 INFO  - Container test-service_0_2c61c149 for site test-service initialized successfully and is ready to serve requests._

**So port - 8080 should be removed from the note section as automatic request mapping do not happen for this port.**

### PR DESCRIPTION
**Pull request by gandhirajan**
On the note section in the following link - https://docs.microsoft.com/en-us/azure/java/spring-framework/deploy-spring-boot-java-app-on-linux#create-a-web-app-on-linux-on-azure-app-service-using-your-container-image , it is stated that "Azure will automatically map Internet requests to embedded Tomcat server that is running on the standard ports of 80 or 8080. "

But this seems to be not working. The automatic mapping happens for just port 80 and for 8080, the mapping needs to be configured in Application settings using WEBSITES_PORT setting.

Closes #80

### CODE REVIEW

**Comment by gandhirajan** [comment]
Hi, Could someone please update me on this PR?

**Comment by MikeDodaro** [comment]
@gandhirajan I'll send this to the engineering team to see if we can get to the bottom of it.

**Comment by gandhirajan** [comment]
@MikeDodaro Thanks Mike.

> @gandhirajan I'll send this to the engineering team to see if we can get to the bottom of it.

Thanks a lot Mike.

**Comment by gandhirajan** [comment]
> @gandhirajan I'll send this to the engineering team to see if we can get to the bottom of it.

Thanks a lot Mike

**Comment by MikeDodaro** [comment]
@gandhirajan The weekend intervened, but today the right people were notified of your sticking point.  Hopefully we’ll get some information this week.

**Comment by gandhirajan** [comment]
> @gandhirajan The weekend intervened, but today the right people were notified of your sticking point. Hopefully we’ll get some information this week.

Thanks Mike

**Comment by gandhirajan** [comment]
> @gandhirajan The weekend intervened, but today the right people were notified of your sticking point. Hopefully we’ll get some information this week.

Hi Mike, Any clue?

**Comment by MikeDodaro** [comment]
I'm not getting any response to my emails.  I'll ping somebody else today.

**Comment by MikeDodaro** [comment]
@gandhirajan  Here is a reply to your question.  We can pursue it further: 

Let me make sure I understand this correctly. “The automatic mapping happens for just port 80 and for 8080, the mapping needs to be configured in Application settings using WEBSITES_PORT setting.” Are you saying there is no automatic port mapping even for port and port 8080, and you must set WEBSITES_PORT?

**Comment by gandhirajan** [comment]
@MikeDodaro Exactly Mike. In my case, the application is running on port - 8080 and I can make it work only with website port setting. The port binding don't happen automatically except for port 80.

**Comment by MikeDodaro** [comment]
@gandhirajan   Here is engineering response:

Ok now I got it. in that case we can just remove port 8080 under the automatic mapping context.
Azure will automatically map Internet requests to embedded Tomcat server that is running on the standard ports of 80 or 8080. However, if you configured your embedded Tomcat server to run on a custom port…

**Comment by gandhirajan** [comment]
> @gandhirajan Here is engineering response:
> 
> Ok now I got it. in that case we can just remove port 8080 under the automatic mapping context.
> Azure will automatically map Internet requests to embedded Tomcat server that is running on the standard ports of 80 or 8080. However, if you configured your embedded Tomcat server to run on a custom port…

@MikeDodaro  Ya Mike we gotta remove port 8080 from automatic mapping context. That's the change I have made in the submitted PR

**Comment by MikeDodaro** [comment]
@gandhirajan I don’t have authorization to merge this PR.  Is that what you want now?  @bmitchell287 can merge when complete.

**Comment by gandhirajan** [comment]
> @gandhirajan I don’t have authorization to merge this PR. Is that what you want now? @bmitchell287 can merge when complete.

@MikeDodaro Merging this PR after review will help others who are encountering this issue as Spring boot app runs in port - 8080 by default and the probability of users hitting this issue is more.

**Comment by bmitchell287** [comment]
@gandhirajan - Thanks for the contribution here. Accepted the PR and it should be live shortly. We really appreciate you taking the time to look at some of these topics and providing great feedback.

@MikeDodaro - merged

**Comment by gandhirajan** [comment]
> @gandhirajan - Thanks for the contribution here. Accepted the PR and it should be live shortly. We really appreciate you taking the time to look at some of these topics and providing great feedback.
> 
> @MikeDodaro - merged

@bmitchell287  @MikeDodaro  Thanks for your time and bringing it to closure.

**Pull request merged**
