### PR TITLE
Review and fix getting-started-with-spring-cloud-function-in-azure

### PR DESCRIPTION
**Pull request by jdubois**
This is a review requested by @Orin-Thomas as part of advocacy's commitment to content freshness.

### CODE REVIEW

**Comment by jdubois** [comment]
The demo code has also been updated on https://github.com/Azure/azure-functions-java-worker/pull/746 and should be merged soon.

**Comment by ShannonLeavitt** [comment]
@KarlErickson

IMPORTANT: When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by KarlErickson** [comment]
@jdubois could you please close this and reopen in azure-dev-docs-pr? Contributions from internal contributors aren't supposed to go through the public repo. Thanks!

**Comment by jdubois** [comment]
Thank you @KarlErickson , closing this PR and replacing it by https://github.com/MicrosoftDocs/azure-dev-docs-pr/pull/5193

**Pull request closed without merging**
