### PR TITLE
Added limitations sections

### PR DESCRIPTION
**Pull request by FreddyAyala**
This section is important because we require to make clear for clients that altough there are many cases that can be handled using AzAPI is not a silver bullet, for example registering features at the subscription level is not supported:

```
resource "azapi_update_resource" "encathost" {
  type      = Microsoft.Features/providers@2021-07-01
  name      = "EncryptionAtHost"
  parent_id = data.azurerm_subscription.current.id

  body = jsonencode({
    properties = {
      featureName = "EncryptionAtHost"
      resourceProviderNamespace = "Microsoft.Compute"
      subscriptionId = data.azurerm_subscription.current.id
    }
  })
}
```

This will not work and have to use the following work around:

```
resource "null_resource" "test" {

  provisioner "local-exec" {
    command = "az feature register --namespace Microsoft.Compute --name EncryptionAtHost'"
  }
} 
```

Therefore it is very important to inform clients and users about AzAPI limitations.

### CODE REVIEW

**Comment by Jak-MS** [comment]
#assign:@MicrosoftDocs/public-repo-pr-review-team

**Comment by grayzu** [comment]
@FreddyAyala Thanks for submitting this PR and your interest in the AzAPI provider. 

This is great call out that we need to add a limitations section so that it is clear what is supported by the current AzAPI resources.  The reason that your example does not work is slightly different than your explanation so we will provide some suggested changes to your PR and get it merged ASAP.

Thank you again for taking the time to submit this PR!!

**Comment by FreddyAyala** [comment]
Thanks Tom I'll be looking forward to it.

Best Regards

Freddy

**Comment by KarlErickson** [comment]
@stemaMSFT @TomArcherMsft @grayzu ping

**Comment by TomArcherMsft** [comment]
@FreddyAyala 
On behalf of our team, I apologize for us not closing this earlier. At this point, I believe we can close the PR as the engineering team has added the `azapi_resource_action`. In addition, the reference documentation calls out at what level a particular resource can be deployed ([example](https://learn.microsoft.com/en-us/azure/templates/microsoft.resources/tags?pivots=deployment-language-terraform)).

**Pull request closed without merging**
