### PR TITLE
Updates YAML schema URL

### PR DESCRIPTION
**Pull request by Sealjay**
Associated issue #850

URL for AZD YAML schema is incorrect

Is
> For full details, refer to [azure.yaml.json](https://github.com/Azure/azure-dev/blob/main/schemas/v1.0/azure.yaml.json/).

Should be
> For full details, refer to [azure.yaml.json](https://azuresdkreleasepreview.blob.core.windows.net/azd/schema/azure.yaml.json).

### CODE REVIEW

**Comment by Jak-MS** [comment]
@hhunter-ms 

Can you review this PR?

IMPORTANT: When this content is ready to merge, you must add `#sign-off` in a comment or the approval may get overlooked.


#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by hhunter-ms** [comment]
Thanks @Jak-MS - under review!

**Comment by hhunter-ms** [comment]
Hi @Sealjay - As mentioned in the linked issue: 
> According to the engineering team, the link originally provided is correct. They used the schema copy on an Azure blob store as a temporary measure before the project was publicly announced.

Hopefully this helps!

**Comment by Sealjay** [comment]
Perfect, ta! The original link was broken / inaccessible (but I see it's working now.) @hhunter-ms

**Pull request closed without merging**
