### PR TITLE
Clarify steps to test node function locally

### PR DESCRIPTION
**Pull request by mlevinem6**
When it says this is a "reminder", it makes me go back to find where I missed a step - but it doesn't seem that is specified anywhere else when going through this tutorial, so it ends up being a waste of time.  This puts the steps in proper order for someone going step by step through this tutorial.

### CODE REVIEW

**Comment by diberry** [comment]
#in-progress

**Comment by diberry** [comment]
If you are using V3 of Functions core tools and the latest Azure Functions extension, these step shouldn't be necessary at all. If you find that it is necessary, can you tell me what version of these 2 tools you are running along with what version of Node.js you are running locally?

**Comment by mlevinem6** [comment]
@diberry Cool, confirmed.  In that case, can I just adjust this PR to get rid of that line altogether instead of moving it?  I'm just trying to make it so people aren't tracing back to see what they missed, as indicated by `remember`.

**Comment by diberry** [comment]
@mlevinem6 - I updated this doc to make sure it matches with v3 of the functions local development. I don't believe a mention of running server is required anymore. I don't think the PR is relevent but if you still feel the text needs to change, please adjust and I'll take a look at it.

**Comment by mlevinem6** [comment]
Changes look great, thank you @diberry !

**Pull request closed without merging**
