### PR TITLE
Update azure-ai-for-developers-dotnet.md

### PR DESCRIPTION
**Pull request by wmwxwa**

### CODE REVIEW

**Comment by wmwxwa** [comment]
#sign-off

**Comment by Jak-MS** [comment]
@mcleanbyron 
- Can you review this PR?
- IMPORTANT: When this content is ready to merge, you must add `#sign-off` in a comment or the approval may get overlooked.


#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by Jak-MS** [comment]
@wmwxwa - Microsoft content pros should be working in the private repo. You might consider closing your recent public repo PRs and re-submitting the changes via the private repo... or you can wait for approvals.

**Comment by KarlErickson** [comment]
CC @alexwolfmsft

**Review by alexwolfmsft — APPROVED** [review]

**Pull request merged**
