### PR TITLE
Simplify by removing unnecessary steps and with sensible defaults

### PR DESCRIPTION
**Pull request by thegovind**
- Parity with https://github.com/MicrosoftDocs/azure-docs-pr/pull/215944 and associated sample https://github.com/Azure-Samples/open-liberty-on-aks
- Removed, or made optional, unnecessary steps
- Added sensible defaults where applicable
- Tested
- Signed off by @m-reza-rahman and reviewed by @majguo

### CODE REVIEW

**Comment by cmcclister** [comment]
Learn Build status updates of commit _[485d35e](https://github.com/thegovind/azure-dev-docs/commits/485d35ec454457bfacf7c97df52b8491aa1a070d)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[articles/java/ee/howto-deploy-java-liberty-app-manual.md](https://github.com/thegovind/azure-dev-docs/blob/patch-1/articles/java/ee/howto-deploy-java-liberty-app-manual.md) | :warning:Warning | | [Details](#user-content-914386d6d87a6aa88e55a4b9a979232c-7887d011)

<a id="914386d6d87a6aa88e55a4b9a979232c-7887d011"></a>
### [articles/java/ee/howto-deploy-java-liberty-app-manual.md](https://github.com/thegovind/azure-dev-docs/blob/patch-1/articles/java/ee/howto-deploy-java-liberty-app-manual.md)
 - **Line 38, Column 180**: **[Warning: file-not-found - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../role-based-access-control/role-assignments-list-portal.md'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/165f6904-aea8-9c51-0a94-fc09f5b5556a/202211060524589536-950/BuildReport?accessString=1fc34d54823a365868902a5ca25278352459c6766705c1434bbc39639bc2bcf3).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.learn.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Learn Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/165f6904-aea8-9c51-0a94-fc09f5b5556a?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.learn.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

**Comment by majguo** [comment]
Similar to https://github.com/MicrosoftDocs/azure-docs-pr/pull/215944, this PR should also be moved to https://github.com/MicrosoftDocs/azure-dev-docs-pr because `azure-dev-docs-pr` is for internal user but `azure-dev-docs` is for external user.

**Comment by majguo** [comment]
Pls also fix all warnings detected by `Learn Build`.

**Comment by majguo** [comment]
Pls also fix warnings detected by `Learn Build`.

**Comment by thegovind** [comment]
@majguo - Fixed the warning related to invalid link. Regarding moving the pr to `azure-dev-docs-pr`, I was looking for this under https://github.com/MicrosoftDocs/azure-docs-pr and couldn't find it, without realizing of the existence of `azure-dev-docs-pr`. Anyway, will follow the same approach as with `azure-docs-pr`. Thanks for pointing this out.

**Comment by cmcclister** [comment]
Learn Build status updates of commit _[1c52537](https://github.com/thegovind/azure-dev-docs/commits/1c525378788ee34dbd28216137b7aa1c69aef431)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[articles/java/ee/howto-deploy-java-liberty-app-manual.md](https://github.com/thegovind/azure-dev-docs/blob/patch-1/articles/java/ee/howto-deploy-java-liberty-app-manual.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/165f6904-aea8-9c51-0a94-fc09f5b5556a/202211070029360095-950/BuildReport?accessString=2ca1863ce6bba6068526fdb3d7e487182e1a249eecb14898e78861f5f3fca78a).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/165f6904-aea8-9c51-0a94-fc09f5b5556a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

**Comment by majguo** [comment]
As @thegovind has already moved the same changes to the PR https://github.com/MicrosoftDocs/azure-dev-docs-pr/pull/3811, I'm going to close this one.

**Comment by majguo** [comment]
#please-close

**Pull request closed without merging**
