### PR TITLE
Update configure spring data gremlin java app with cosmos db

### PR DESCRIPTION
**Pull request by chenrujun**

### CODE REVIEW

**Comment by chenrujun** [comment]
Related PR: https://github.com/Azure/azure-sdk-for-java/pull/13414

**Comment by ktoliver** [comment]
Hi @bmitchell287 - Please review. It looks like @chenrujun is set up to work in the private repo (member of MicrosoftDocs). Should they submit this update in the private repo instead of in the public repo?

**Comment by chenrujun** [comment]
Hi, @ktoliver .
I created a PR in private repo: https://github.com/MicrosoftDocs/azure-dev-docs-pr/pull/834

**Comment by ktoliver** [comment]
Thanks @chenrujun! I left a comment in the new PR about what to expect next.

**Pull request closed without merging**
