### PR TITLE
Clarify permissions on resource group scoped deployment

### PR DESCRIPTION
**Pull request by weikanglim**
Add a clarifying note that explains how resource group scoped deployments affect permissions needed since there's been recent user asks around it.

### CODE REVIEW

**Comment by weikanglim** [comment]
@gkulin  @alexwolfmsft FYI

**Comment by rajeshkamal5050** [comment]
@weikanglim can we also callout the required roles/permissions for the rg scoped deployments?

**Comment by Court72** [comment]
@gkulin

Can you review the proposed changes? 

When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Review by gkulin — APPROVED** [review]

**Comment by gkulin** [comment]
#sign-off

**Pull request merged**
