### PR TITLE
Fix #65: Including missed step in the tutorial (Node.js version/runtime)

### LINKED ISSUE #65: [Doc Report] Missed step in the tutorial (Node.js version/runtime)
**Link Page 04:** https://docs.microsoft.com/en-us/azure/javascript/tutorial-vscode-serverless-node-04 

In this part of this tutorial is missing a step to choose which Node.js version/runtime you should use (as you can see in the demo)

[](https://postimg.cc/jwGPcY2Q)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6f600e51-0ee3-ea85-d183-3d21c7a86efc
* Version Independent ID: 97c4f2ff-9ac0-9fe0-34b2-b03b719dda91
* Content: [Deploy the Azure Functions application from Visual Studio Code](https://docs.microsoft.com/en-us/azure/javascript/tutorial-vscode-serverless-node-04)
* Content Source: [javascript/tutorial-vscode-serverless-node-04.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/javascript/tutorial-vscode-serverless-node-04.md)
* Product: **azure-nodejs**
* GitHub Login: @kraigb
* Microsoft Alias: **kraigb**

### PR DESCRIPTION
**Pull request by glaucia86**
Including missed step in the tutorial (Node.js version/runtime)

### CODE REVIEW

**Comment by glaucia86** [comment]
Pull Request relationated to the issue: #65 

cc: @kraigb

**Comment by glaucia86** [comment]
@kraigb I did the requested changes: [here](https://github.com/MicrosoftDocs/azure-dev-docs/pull/66/commits/37e89181ead060fb2eefc326d658e8c52ef6a52f)

**Comment by kraigb** [comment]
@glaucia86 Hmmm...the graphic is still oversized. Go to Files changed, select the ... for the file, and select View File to see how it's still scaled. But I think you can mitigate this by simply cropping the image to show only the prompt and the two Node.js choices, trimming off most of the width. Then it looks more natural to be zoomed in. When the graphic is this wide, we waste a lot of real estate on essentially empty parts of the prompt, which is there only because you're trying to include the heading on the top, which isn't needed.

**Comment by glaucia86** [comment]
> @glaucia86 Hmmm...the graphic is still oversized. Go to Files changed, select the ... for the file, and select View File to see how it's still scaled. But I think you can mitigate this by simply cropping the image to show only the prompt and the two Node.js choices, trimming off most of the width. Then it looks more natural to be zoomed in. When the graphic is this wide, we waste a lot of real estate on essentially empty parts of the prompt, which is there only because you're trying to include the heading on the top, which isn't needed.

Awe! I resized from: **1089 x 205** to **545 x 103**

Now is this way:

[](https://postimg.cc/2Lbdb4w1)

Comminting now!

**Comment by kraigb** [comment]
Thanks, that works.

**Pull request merged**
