### PR TITLE
Wrong Quarkus config properties used in the Deploy Microprofile article

### PR DESCRIPTION
**Pull request by loicmathieu**

### CODE REVIEW

**Comment by cmcclister** [comment]
Learn Build status updates of commit _[15b7bcf](https://github.com/loicmathieu/azure-dev-docs/commits/15b7bcf5a598d5278acb8275b9e2fc86de50c909)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[articles/java/eclipse-microprofile/deploy-microprofile-quarkus-java-app-with-maven-plugin.md](https://github.com/loicmathieu/azure-dev-docs/blob/fix-quarkus-config/articles/java/eclipse-microprofile/deploy-microprofile-quarkus-java-app-with-maven-plugin.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/165f6904-aea8-9c51-0a94-fc09f5b5556a/202212291224496042-1003/BuildReport?accessString=5bb36c55c1d8e97e68e710c79137cc816d8b6f583d85e5888372f05a909b0520).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/165f6904-aea8-9c51-0a94-fc09f5b5556a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

**Review by brunoborges — APPROVED** [review]
Lgtm

**Comment by jborsecnik** [comment]
@KarlErickson, 

Can you review the proposed changes? 

IMPORTANT: When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by jborsecnik** [comment]
@KarlErickson, 

Can you review the proposed changes? 

IMPORTANT: When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by KarlErickson** [comment]
@loicmathieu thanks for the update!

**Pull request merged**
