### PR TITLE
Update azure-sdk-authenticate-hosted-applications.md

### PR DESCRIPTION
**Pull request by lmazuel**
This steps may be still interesting, but should not be recommended to customers

### CODE REVIEW

**Comment by ShannonLeavitt** [comment]
@KarlErickson - Would you be able to review and approve these proposed changes?

#label:"aq-pr-triaged"

**Comment by KarlErickson** [comment]
@jess-johnson-msft ping

**Comment by jess-johnson-msft** [comment]
@DavidCBerry13  - I added you as a reviewer for this PR, as you have been contributing and expanding the Python SDK Auth content.

**Comment by KarlErickson** [comment]
@DavidCBerry13 ping

**Comment by DavidCBerry13** [comment]
Closing this issue because we have just reworked the whole SDK auth section and this file has been replaced by new content.  Working with Laurent though to make sure the intent of this change is captured in the new content.

**Pull request closed without merging**
