### PR TITLE
Fix typo in title

### PR DESCRIPTION
**Pull request by pamelafox**

### CODE REVIEW

**Comment by Jak-MS** [comment]
@

**Comment by pamelafox** [comment]
Not sure why that error is being reported for terraform article, as thats not in my PR

**Comment by pamelafox** [comment]
#sign-off

**Comment by pamelafox** [comment]
#ready-to-merge

**Comment by Court72** [comment]
#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by pamelafox** [comment]
Opened https://github.com/MicrosoftDocs/azure-dev-docs-pr/pull/4545

**Pull request closed without merging**
