### PR TITLE
Update storage and key vault to new ref experience

### PR DESCRIPTION
**Pull request by maggiepint**

### CODE REVIEW

**Comment by KarlErickson** [comment]
Hi @maggiepint - this is an autogenerated file so we shouldn't make direct updates to it. Instead, please file an issue at <https://github.com/Azure/azure-sdk/issues> and assign it to weshaggard. (Also, FYI, we prefer internal folks to file PRs for this repo using the internal azure-dev-docs-pr instead - thanks!)

**Comment by maggiepint** [comment]
Hey @KarlErickson sorry I wasn't entirely clear about this PR. It is my intention to edit the auto-generated file. We have a user study that is going to run for just a couple days that uses alternative ref documentation for just those two services. Dina and I agreed to just not merge the auto updates while the study was running. I also need to update one other include file, but they will only be changed for a couple days.

**Comment by maggiepint** [comment]
I can PR on the internal repo if you like.

**Comment by KarlErickson** [comment]
@maggiepint the azure-sdk bot creates multiple PRs per day that combine all the autogenerated files. I merge these PRs every now and then. It would be easiest to just hold off on merging any of these files until you are done with your study. I will add a note to the next azure-sdk PR. Thanks for the info!

**Pull request closed without merging**
