### PR TITLE
Fixed flask clone url

### PR DESCRIPTION
**Pull request by fbrettnich**
Signed-off-by: fbrettnich <github@fbrettnich.de>

### CODE REVIEW

**Comment by cmcclister** [comment]
Learn Build status updates of commit _[d98745c](https://github.com/fbrettnich/azure-dev-docs/commits/d98745ca1f8269ae2e596bb722bff323f24085a7)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[articles/python/tutorial-containerize-deploy-python-web-app-azure-02.md](https://github.com/fbrettnich/azure-dev-docs/blob/main/articles/python/tutorial-containerize-deploy-python-web-app-azure-02.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/165f6904-aea8-9c51-0a94-fc09f5b5556a/202212201304473484-996/BuildReport?accessString=d7170ffbb59dd7f47cfb4d7e93d31c5a56efb70415fdd127803a5d279adb3946).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/165f6904-aea8-9c51-0a94-fc09f5b5556a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

**Comment by Court72** [comment]
@diberry

Can you review the proposed changes? 

When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by KarlErickson** [comment]
@diberry ping

**Review by diberry — APPROVED** [review]
Thank you for submitting the fix.

**Comment by diberry** [comment]
#sign-off

**Pull request merged**
