### PR TITLE
Update vm-configure-windows.md for new ansible script location

### PR DESCRIPTION
**Pull request by jgsqware**
Ansible script to init has changed location, This change updates it

### CODE REVIEW

**Comment by Court72** [comment]
@TomArcherMsft

Can you review the proposed changes? 

When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by KarlErickson** [comment]
@TomArcherMsft ping

**Comment by KarlErickson** [comment]
@TomArcherMsft ping

**Comment by TomArcherMsft** [comment]
Thanks @jgsqware for the contribution. #sign-off

**Pull request merged**
