### PR TITLE
Updated Spring Data Cosmosdb dev guide to reflect v3 support

### PR DESCRIPTION
**Pull request by rinatmini**
[Internal Supportability workitem](https://msdata.visualstudio.com/CosmosDB/_workitems/edit/2550050/)

Related [Public Doc update PR](https://github.com/MicrosoftDocs/azure-docs-pr/pull/246125).

### CODE REVIEW

**Comment by rinatmini** [comment]
@kushagraThapar please review this

[Internal Supportability workitem](https://msdata.visualstudio.com/CosmosDB/_workitems/edit/2550050/)

Related changes [Public Doc update PR](https://github.com/MicrosoftDocs/azure-docs-pr/pull/246125).

**Review by kushagraThapar — APPROVED** [review]
We can't update this document like this, it will overwrite the existing information. Let's discuss this offline.

**Review by kushagraThapar — CHANGES_REQUESTED** [review]
We can't overwrite this document. Let's discuss this offline.

**Comment by Court72** [comment]
#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by rinatmini** [comment]
No changes are needed. Already has links to the actual info.

**Pull request closed without merging**
