### PR TITLE
Typo "Azure Monitor's"→"Azure Monitor"

### PR DESCRIPTION
**Pull request by hyoshioka0128**
https://learn.microsoft.com/en-us/azure/developer/javascript/how-to/node-sdk-logging 
https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/javascript/how-to/node-sdk-logging.md 
#PingMSFTDocs

### CODE REVIEW

**Comment by cmcclister** [comment]
Learn Build status updates of commit _[42ccf73](https://github.com/hyoshioka0128/azure-dev-docs/commits/42ccf7350f995015e9beaa2ef4327b6838a40a06)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[articles/javascript/how-to/node-sdk-logging.md](https://github.com/hyoshioka0128/azure-dev-docs/blob/patch-23/articles/javascript/how-to/node-sdk-logging.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/165f6904-aea8-9c51-0a94-fc09f5b5556a/202211061543254924-951/BuildReport?accessString=dde1a78e52d10ce18d05da4e543df27eca49370663946639d4ceca4ef1f21c61).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/165f6904-aea8-9c51-0a94-fc09f5b5556a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

**Review by diberry — APPROVED** [review]
Thank you for the correction.

**Comment by diberry** [comment]
#sign-off

**Review by jborsecnik — APPROVED** [review]

**Comment by cmcclister** [comment]
Learn Build status updates of commit _[42ccf73](https://github.com/hyoshioka0128/azure-dev-docs/commits/42ccf7350f995015e9beaa2ef4327b6838a40a06)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[articles/javascript/how-to/node-sdk-logging.md](https://github.com/hyoshioka0128/azure-dev-docs/blob/patch-23/articles/javascript/how-to/node-sdk-logging.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/165f6904-aea8-9c51-0a94-fc09f5b5556a/202211072117129310-951/BuildReport?accessString=dc04c2992932a24b0798a16b75601132a26a2e855114f5221422fe913ba8a223).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/165f6904-aea8-9c51-0a94-fc09f5b5556a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

**Pull request merged**
