### PR TITLE
Update deploy-passwordless-spring-database-app.md

### PR DESCRIPTION
**Pull request by xfz11**
Add some note

### CODE REVIEW

**Comment by cmcclister** [comment]
Learn Build status updates of commit _[4ffccda](https://github.com/xfz11/azure-dev-docs/commits/4ffccdabe979c5e3a5449f0185c473398384aeb8)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[articles/java/spring-framework/deploy-passwordless-spring-database-app.md](https://github.com/xfz11/azure-dev-docs/blob/patch-2/articles/java/spring-framework/deploy-passwordless-spring-database-app.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/165f6904-aea8-9c51-0a94-fc09f5b5556a/202210270920551100-936/BuildReport?accessString=19638b4f62fefaffa1c51fc140e9fefd6051bbb3873144195952eb92dfc0a97c).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/165f6904-aea8-9c51-0a94-fc09f5b5556a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

**Comment by cmcclister** [comment]
Learn Build status updates of commit _[8f87636](https://github.com/xfz11/azure-dev-docs/commits/8f87636c49e56a4414a92d90e921573469dc5fd2)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[articles/java/spring-framework/deploy-passwordless-spring-database-app.md](https://github.com/xfz11/azure-dev-docs/blob/patch-2/articles/java/spring-framework/deploy-passwordless-spring-database-app.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/165f6904-aea8-9c51-0a94-fc09f5b5556a/202210270923038083-936/BuildReport?accessString=140edba5cebb674bc1b6ff00964201329505d7acf3ab56afff556fad9da09ffa).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/165f6904-aea8-9c51-0a94-fc09f5b5556a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

**Comment by KarlErickson** [comment]
@saragluna can you please validate? Thanks!

**Review by saragluna — APPROVED** [review]
LGTM, thanks.

**Comment by saragluna** [comment]
Could you explain more @xfz11, like how to check whether my Python and az are 64-bit? When we test the command using the private-preview version, why did it work then, does it mean the az we installed is 64-bit?

**Comment by cmcclister** [comment]
Learn Build status updates of commit _[08bce8c](https://github.com/xfz11/azure-dev-docs/commits/08bce8c925f53ea3131e6cf8944c0ba5e30d0dc6)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[articles/java/spring-framework/deploy-passwordless-spring-database-app.md](https://github.com/xfz11/azure-dev-docs/blob/patch-2/articles/java/spring-framework/deploy-passwordless-spring-database-app.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/165f6904-aea8-9c51-0a94-fc09f5b5556a/202210280341459241-936/BuildReport?accessString=9414af9693e51058cb3ab90f552bcb425a190215be8dc6c3be55e4bb50da1848).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/165f6904-aea8-9c51-0a94-fc09f5b5556a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

**Comment by xfz11** [comment]
> Could you explain more @xfz11, like how to check whether my Python and az are 64-bit? When we test the command using the private-preview version, why did it work then, does it mean the az we installed is 64-bit?

Yes, I update the note with more detail. 
When we use private-preview version, we install CLI with Python whl files, which will use 64-bit Python on our machine. But if users install CLI with MSI, then it use an embedded 32-bit python.

**Comment by cmcclister** [comment]
Learn Build status updates of commit _[5ab940a](https://github.com/xfz11/azure-dev-docs/commits/5ab940a9f6687fdc2666ce9cbdf144879d511403)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[articles/java/spring-framework/deploy-passwordless-spring-database-app.md](https://github.com/xfz11/azure-dev-docs/blob/patch-2/articles/java/spring-framework/deploy-passwordless-spring-database-app.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/165f6904-aea8-9c51-0a94-fc09f5b5556a/202210280342429171-936/BuildReport?accessString=cce1a17aea2c8c6a0ba92264c28c931aa003ee2122c665da8d871b53232ab6b7).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/165f6904-aea8-9c51-0a94-fc09f5b5556a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

**Comment by jborsecnik** [comment]
@saragluna 

IMPORTANT: When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge. 

Thanks.

**Comment by saragluna** [comment]
#sign-off

**Pull request merged**
