### PR TITLE
Update deploy-passwordless-spring-database-app.md

### PR DESCRIPTION
**Pull request by xfz11**
Add SQL dependency on Prerequisites section

### CODE REVIEW

**Comment by cmcclister** [comment]
Learn Build status updates of commit _[56b6990](https://github.com/xfz11/azure-dev-docs/commits/56b699020e321edd3f7375330ae4640ab727f8bf)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[articles/java/spring-framework/deploy-passwordless-spring-database-app.md](https://github.com/xfz11/azure-dev-docs/blob/patch-1/articles/java/spring-framework/deploy-passwordless-spring-database-app.md) | :warning:Warning | | [Details](#user-content-96e07c1d7600eed63d7484c35367d2fb-8c19646f)

<a id="96e07c1d7600eed63d7484c35367d2fb-8c19646f"></a>
### [articles/java/spring-framework/deploy-passwordless-spring-database-app.md](https://github.com/xfz11/azure-dev-docs/blob/patch-1/articles/java/spring-framework/deploy-passwordless-spring-database-app.md)
 - **Line 33, Column 3**: **[Warning: hard-coded-locale - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://learn.microsoft.com/en-us/sql/connect/odbc/download-odbc-driver-for-sql-server?view=sql-server-ver16' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 33, Column 3**: **[Suggestion: docs-link-absolute - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://learn.microsoft.com/en-us/sql/connect/odbc/download-odbc-driver-for-sql-server?view=sql-server-ver16' will be broken in isolated environments. Replace with a relative link.`````
 - **Line 33, Column 3**: **[Suggestion: preserve-view-not-set - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````You've pinned this link to a specific version of content with the view parameter. It's recommended not to pin a version unless that version is A) not the default view and B) the context is about that version specifically. To proceed with pinning a version add the &preserve-view=true to the URL.  Otherwise, remove the view parameter. URL: https://learn.microsoft.com/en-us/sql/connect/odbc/download-odbc-driver-for-sql-server?view=sql-server-ver16`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/165f6904-aea8-9c51-0a94-fc09f5b5556a/202210250346252199-930/BuildReport?accessString=51fd312b8eb782098b9544083dc6b9aeba9997bbb550813a6bc96af3c4ecc43a).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.learn.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Learn Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/165f6904-aea8-9c51-0a94-fc09f5b5556a?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.learn.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

**Comment by cmcclister** [comment]
Learn Build status updates of commit _[2233f3a](https://github.com/xfz11/azure-dev-docs/commits/2233f3a21d4ee97bd7b878befafc8e5c521bae80)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[articles/java/spring-framework/deploy-passwordless-spring-database-app.md](https://github.com/xfz11/azure-dev-docs/blob/patch-1/articles/java/spring-framework/deploy-passwordless-spring-database-app.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/165f6904-aea8-9c51-0a94-fc09f5b5556a/202210250353038261-930/BuildReport?accessString=20634c46320a2dd2c2cf44c84466097d895a2546d1c530163a9cbb9cdae639ce).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/165f6904-aea8-9c51-0a94-fc09f5b5556a?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

**Comment by Court72** [comment]
@KarlErickson 

Can you review the proposed changes? *IMPORTANT*: When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by KarlErickson** [comment]
Thanks, @xfz11!

@saragluna can you please validate? Thanks!

**Review by saragluna — APPROVED** [review]
LGTM. Thanks!

**Pull request merged**
