### PR TITLE
Typo "Docker explorer"→"Docker Explorer"

### PR DESCRIPTION
**Pull request by hyoshioka0128**
https://docs.microsoft.com/en-us/azure/developer/javascript/tutorial/tutorial-vscode-docker-node/tutorial-vscode-docker-node-02
#PingMSFTDocs

### CODE REVIEW

**Comment by diberry** [comment]
@hyoshioka0128 Thank you for the PR. Unfortunately, it is introducing problems in both lines instead of fixing issues. What issues are you trying to solve? 

#hold-off

**Comment by diberry** [comment]
@hyoshioka0128 Can you please fix lines 48 and 49?

**Comment by ktoliver** [comment]
I've fixed what looks like a stray keystroke error. Also, the alt text for the first image shouldn't mention Docker, because it looks like you aren't using Docker or Docker Explorer yet at that point in the procedure; I've modified.

**Comment by diberry** [comment]
@ktoliver - thank you - feel free to merge.

**Comment by ktoliver** [comment]
Thanks, all.

**Pull request merged**
