### PR TITLE
The link for JS/TS samples appears to be broken

### PR DESCRIPTION
**Pull request by richardpark-msft**
I've just redone it using what I think is the same criteria (nodejs, javascript, typescript).

### CODE REVIEW

**Comment by ktoliver** [comment]
I've verified the link (syntax) fix, so I'll merge the PR. Thanks @richardpark-msft

**Comment by richardpark-msft** [comment]
Btw, some positive feedback - I really liked how easy it was to both look at the content and then figure out where to edit it. Whomever did that work deserves some kudos :)

**Comment by diberry** [comment]
#hold-off

**Comment by ktoliver** [comment]
Hi @diberry - I confirmed the fix that was submitted in the pull request and merged the pull request this morning. The link works correctly now on the live site: https://docs.microsoft.com/en-us/azure/developer/javascript/

@tfosmark

**Comment by diberry** [comment]
@ktoliver Yes, I appreciate the proactive nature. The issue is all of the links in that section are broken because of the query string syntax. I was in the middle of a different direction. Maybe next time, can you give me a day before merging?

**Pull request merged**
