### PR TITLE
Update intelligent-app-templates-java.md

### PR DESCRIPTION
**Pull request by dantelmomsft**

### CODE REVIEW

**Comment by Court72** [comment]
@ms-johnalex

Can you review the proposed changes? Note that the commits need to be [moved into the private repo](https://review.learn.microsoft.com/help/contribute/contribute-how-to-manage-act-guidelines-public-pr?branch=main#pull-public-commits-to-the-private-repo-for-updates-staging-publication) for staging and automated checks. Let us know if you'd like the PR review team's help moving the commits.
	

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by KarlErickson** [comment]
@dantelmomsft thanks for the pull request! However, internal contributors should submit PRs to the internal docs repo azure-dev-docs-pr. Could you please close this PR and recreate it there? Thanks!

**Comment by dantelmomsft** [comment]
@KarlErickson didn't find any azure-dev-docs-pr repo or maybe I don't access to it.. can you please help me

**Comment by KarlErickson** [comment]
@dantelmomsft you'll need to join the MicrosoftDocs org first, then you should be able to access azure-dev-docs-pr.

**Comment by dantelmomsft** [comment]
@KarlErickson  new PR here: https://github.com/MicrosoftDocs/azure-dev-docs-pr/pull/6335. Will close this one.

**Pull request closed without merging**
